#!/bin/sh

pip install -r requirements.txt

# Install spacy models
# https://spacy.io/
python -m spacy download xx_sent_ud_sm
python -m spacy download en_core_web_sm

# Install Argos Translate 2 beta
# https://www.argosopentech.com/
git clone https://github.com/argosopentech/argos-translate.git
cd argos-translate
git checkout v2
pip install -e .
cd ..
argospm install chunk

# Install Stanza models
# https://github.com/stanfordnlp/stanza
python -c 'import stanza; stanza.download("en")'
